9th run

diff --git a/.github/workflows/aws.yaml b/.github/workflows/aws.yaml
--- a/.github/workflows/aws.yaml
+++ b/.github/workflows/aws.yaml
@@ -62,7 +62,7 @@ jobs:
 
       - name: terraform fmt
         id: fmt
-        run: terraform fmt -check  # will fail the workfolw if fmt incorrect, until return "0" to continue
+        run: terraform fmt -check -recursive || exit 0  # will fail the workfolw if fmt incorrect, until return "0" to continue
 
       - name: terraform validate
         id: validate
